
## Methods {.tabset}

### Figure 1

```{r, include = FALSE}

# Plot maps of DR and of Caribbean region for Figure 6

DR_subnational <- st_read(here("data", "geographical", "gadm36_DOM_shp", "gadm36_DOM_2.shp"))

selected_clusters <- read.csv("/Users/emiliefinch/Projects/DR-covid/geographical_data/selected_clusters.csv") 

selected_clusters <- selected_clusters %>% 
  mutate(urban_rural = as.factor(Classification))

cluster_map <- ggplot() +
  geom_sf(data = DR_subnational, fill = "#d5dce3",  color = "#014636", size = 0.2) +  
  #geom_sf(data = subset(DR_subnational, NAME_2 == "San Pedro de Macorís" | NAME_2 == "Moca" | NAME_2 == "Santiago de los Caballeros"),  fill = "#0570b0", alpha = 0.5, color = "#045a8d", size = 0.2) +
  geom_jitter(data = selected_clusters, aes(x = Long, y = Lat), col = ("#016c59"), size = 1.2, shape = 16) +
  guides(x = "none", y = "none") +
  coord_sf() +
  labs(x = NULL, y = NULL) +
  theme_void() + theme(legend.position = "bottom", legend.title = element_blank()) +
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm")) +
  scale_x_continuous(expand = c(0.01,0.01)) + scale_y_continuous(expand = c(0.01,0.01))

caribs <- st_read(here("data", "geographical",  "caribis", "caribis.shp"))

coords <- as.data.frame(st_centroid(caribs$geometry))
coords <- separate(coords, geometry, into = c("long", "lat"), sep = " ")
coords$long <- gsub("[^0-9.-]", "", coords$long)
coords$lat <- gsub("[^0-9.-]", "", coords$lat)

coords <- coords %>% mutate(long = as.numeric(long), lat = as.numeric(lat))

caribs$long <-coords$long
caribs$lat <-coords$lat

plot_ratio <- get_asp_ratio(caribs)

plot_carib <- ggplot() +
  geom_sf(data = caribs, fill = "#d5dce3",  color = "#014636", size = 0.2) +  
  #geom_text(data = caribs, aes(long, lat, label = CNTRY_NAME), size = 1) +
  geom_rect(aes(xmin = -72.20307, xmax = -68.12224, ymin = 17.3 , ymax =20.2), fill = NA, col = "#014636", size = 0.4) +
  guides(x = "none", y = "none") +
  coord_sf() +
  labs(x = NULL, y = NULL) +
  theme_void() + theme(legend.position = "bottom", legend.title = element_blank()) +
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm")) +
  scale_x_continuous(expand = c(0.01,0.01)) + scale_y_continuous(expand = c(0.01,0.01))


maps <- ggarrange(plot_carib, cluster_map, labels = c("a", "b"), vjust = 2, font.label = list(size = 16, font = plot_font))


```

```{r, fig.width = 15, fig.height = 12}

# Plot case time series for Figure 6


covid19_cases <- read.csv(here("data", "covid19-cases_dom-rep.csv")) |> 
  mutate(date = as.Date(date, format = "%d/%m/%Y"))

pal <- met.brewer("Isfahan1", n = 12, type = "continuous")

plot_cases <- ggplot(covid19_cases, aes(x= date, y = new_cases)) +
  geom_col(alpha = 0.6, fill = pal[9], width = 1.025) + #"#02818a"
  geom_ma(ma_fun = SMA, n = 7, alpha = 1, lty = "solid", size = 0.5, col = "#016c59") +
  #geom_line(aes(x = date, y = test_positivity_14_day_smooth*100*100), size = 0.5, col = pal[10]) + #"#016c59"
  xlab("Date Confirmed") + ylab("COVID-19 cases \n") +
  scale_y_continuous(breaks = seq(0,3000, by = 1000)) +
  geom_vline(aes(xintercept = as.Date("2020-03-19")), size = 0.3,  col = "#737373") +
  annotate("text", x=as.Date("2020-04-14"), y=3000, label="State of \n emergency", size = 4,  family = plot_font, col = "black") +
  geom_vline(aes(xintercept = as.Date("2021-02-16")), size = 0.3,  col = "#737373") +
  annotate("text", x=as.Date("2021-03-19"), y=3000, label="Vaccination \n starts", size = 4,  family = plot_font, col = "black") +
  geom_vline(aes(xintercept = as.Date("2021-10-11")), size = 0.3,  col = "#737373") +
  annotate("text", x=as.Date("2021-11-21"), y=3000, label="Curfew and state \n of emergency lifted", size = 4,  family = plot_font, col = "black") +
  annotate("rect", xmin = as.Date("2021-06-30"), xmax = as.Date("2021-10-12"), ymin = -1, ymax = 3000,
           alpha = .2, fill = "grey") +
  theme_classic() +
  scale_x_date(breaks = "1 month", labels = scales::label_date_short(), limits = c(as.Date("2020-03-01"), as.Date("2021-12-15"))) +
  theme(axis.text.x = element_text(hjust = 1, size = 11, family = plot_font), axis.text.y = element_text(size = 10, family = plot_font), axis.title = element_text(size = 12, family = plot_font))


fig_1 <- ggarrange(maps, plot_cases, nrow = 2, heights = c(1, 0.75), labels = c("", "c"), vjust =-1, font.label = list(size = 14))
ggsave(filename = here(output_folder, "figure-1.tiff"), fig_1, width = 360, height = 270, units = "mm", bg="white", dpi = 300, )

fig_1

```

### Figure 2


```{r, include = FALSE}

# Wrangle mobility data to weekly format

googmo <- read.csv(here("data", "google-mobility_dom-rep.csv")) %>% 
  mutate(date = as.Date(date, format = "%d/%m/%Y"))

# Weekly average

gmobility_weekly <- googmo %>%
  mutate(week = floor_date(date, 'week')) %>%
  group_by(week) %>%
  summarise(retail_and_recreation = mean(retail_and_recreation_percent_change_from_baseline, na.rm = TRUE), 
            grocery_and_pharmacy = mean(grocery_and_pharmacy_percent_change_from_baseline, na.rm = TRUE),
            transit_stations = mean(transit_stations_percent_change_from_baseline, na.rm = TRUE),
            workplaces = mean(workplaces_percent_change_from_baseline, na.rm = TRUE),
            residential = mean(residential_percent_change_from_baseline, na.rm = TRUE),
            parks = mean(parks_percent_change_from_baseline, na.rm = TRUE)) 

gmobility_weekly <- gmobility_weekly %>% 
  mutate(other_average = (transit_stations + grocery_and_pharmacy + retail_and_recreation)/3)

gmobility_weekly[,2:8] <- (1+gmobility_weekly[,2:8]/100)

# Long format for plotting

gmobility_weekly <- gmobility_weekly %>%
  dplyr::select(week, retail_and_recreation, grocery_and_pharmacy, workplaces, residential, parks, other_average) %>%
  gather(key = "variable", value = "value", - c(week)) 


```

```{r}

# Mobility data

cols <- brewer.pal(6, "PuOr")

plot_gmobility <- ggplot(gmobility_weekly, aes(x= week, y = value, color = variable)) +
  geom_line() + labs(x = "Date", y = "Population mobility\nrelative to pre-pandemic baseline")  +
  geom_hline(yintercept = 1, lty = "longdash") +
  scale_color_manual(name = "",
                     labels = c("Grocery and Pharmacy", "Other Average", "Parks", "Residential", "Retail and Recreation", "Workplaces"), values = cols) + 
  scale_x_date(breaks = "1 month", labels = scales::label_date_short(), limits = c(as.Date("2020-03-01"), as.Date("2021-12-15"))) +
  theme_classic() +
  theme(axis.text = element_text(size = 10.5, family = plot_font), axis.title = element_text(size = 12, family = plot_font), legend.position = "bottom",
        legend.text = element_text(size = 10.5, family = plot_font)) 

```

```{r, include = FALSE}

# Age-stratified vaccination plot

source(here("R", "00_load-data.R"))

total_vaccs <- rep(0,16)
prop_vaccinated <- NULL
df_vaccinated <- data.frame(time_step = numeric(),
                            age_group = numeric(),
                            percentage = numeric(),
                            new_vaccs = numeric(),
                            cumulative_vaccs = numeric())

df <- c()
for(v in 1:length(vacc[[1]]$v)){
  total_vaccs <- total_vaccs + vacc[[1]]$v[[v]]
  prop_vaccinated[[v]] <- total_vaccs/age_pops*100
  for(age in 1:length(age_pops)){ 
    df$time_step <- as.numeric(v)
    df$age_group <- as.numeric(age)
    df$percentage <- prop_vaccinated[[v]][age]
    df$new_vaccs <- vacc[[1]]$v[[v]][age]
    df$cumulative_vaccs <- total_vaccs[age]
    df_vaccinated <- rbind(df_vaccinated, df)
  }
}

df_vaccinated <- as.data.frame(df_vaccinated)

# Plot percentage vaccinated by age group to check
age_labs <- c("0-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75+")
df_vaccinated$age_group <- factor(df_vaccinated$age_group, labels = age_labs)

```

```{r}

cols <- colorRampPalette(brewer.pal(11, "BrBG")[-6])(12)

prop_vaccinated <- ggplot(df_vaccinated |> filter(age_group != "0-4" & age_group != "5-9" & age_group != "10-14" & age_group != "15-19")) +
  geom_line(aes(x = as.Date("2021-02-15") + time_step, y = percentage, group = factor(age_group), col = factor(age_group))) +
  geom_hline(aes(yintercept = 100), lty = "dashed") + 
  scale_y_continuous(breaks = seq(0,110, by = 10)) +
  labs(x = "Date", y = "Percentage of age group fully vaccinated", col = "Age Group") +
  scale_x_date(breaks = "1 month", labels = scales::label_date_short(), limits = c(as.Date("2021-03-01"), as.Date("2021-12-15"))) +
  scale_color_manual(values = cols) +
  theme_classic() +
  theme(axis.text = element_text(size = 10.5, family = plot_font), axis.title = element_text(size = 12, family = plot_font), legend.position = "right",
        legend.text = element_text(size = 10.5, family = plot_font), legend.title = element_text(size = 12, family = plot_font)) 


```

```{r, include = FALSE}

gisaid <- read.csv(file = here("data", "gisaid-sequences_dom-rep.csv"))

gisaid <- gisaid %>% clean_names() %>% 
  mutate(date = as.Date(date)) %>% 
  mutate(clade2 = case_when(grepl("AY", pangolin_lineage, ignore.case = TRUE) ~ "Delta",
                            grepl("B.1.1.7", pangolin_lineage, ignore.case = TRUE) ~ "Alpha",
                            grepl("B.1.617.2", pangolin_lineage, ignore.case = TRUE) ~ "Delta",
                            grepl("BA.1", pangolin_lineage, ignore.case = TRUE) ~ "BA.1",
                            grepl("BA.2", pangolin_lineage, ignore.case = TRUE) ~ "BA.2",
                            grepl("BA.4", pangolin_lineage, ignore.case = TRUE) ~ "BA.4/5",
                            grepl("BA.5", pangolin_lineage, ignore.case = TRUE) ~ "BA.4/5",
                            grepl("P.1", pangolin_lineage, ignore.case = TRUE) ~ "Gamma",
                            grepl("B.1.621", pangolin_lineage, ignore.case = TRUE) ~ "Mu",
                            grepl("C.37", pangolin_lineage, ignore.case = TRUE) ~ "Lambda",
                            grepl("BQ", pangolin_lineage, ignore.case = TRUE) ~ "BA.4_5",
                            grepl("BF", pangolin_lineage, ignore.case = TRUE) ~ "BA.4_5",
                            grepl("XAM", pangolin_lineage, ignore.case = TRUE) ~ "Recombinant Omicron",
                            grepl("XAM", pangolin_lineage, ignore.case = TRUE) ~ "Recominant Omicron",
                            grepl("Unassigned", pangolin_lineage, ignore.case = TRUE) ~ "Unassigned",
                            TRUE ~ "Other")) %>% 
  mutate(voc = case_when(clade2 == "Other" | clade2 == "Unassigned" ~ "No",
                         TRUE ~ "Yes"))
```

```{r, include = FALSE}

# Frequency (weekly resolution)
cols <- c("Alpha" = "#F8766D", "BA.1" = "#DE8C00", "BA.2" = "#B79F00", "BA.4/5" = "#7CAE00", "Delta" = "#00BA38", "Gamma" = "#00C08B", "Iota" = "#00BFC4", "Lambda" = "#00B4F0", "Mu" = "#619CFF", "Omicron_Unassigned" = "#C77CFF", "Recombinant Omicron" = "#F564E3", "Other" = "#FF64B0")

gisaid_freq <- gisaid %>% 
  mutate(week_date = floor_date(date, unit = "week", week_start = 1)) %>% 
  group_by(week_date, clade2) %>% 
  summarise(n = n()) %>% 
  group_by(week_date) %>% 
  mutate(total = sum(n)) %>%
  ggplot() +
  geom_col(aes(x = week_date, y = n, fill = clade2)) +
  scale_x_date(breaks = "2 months", labels = scales::label_date_short(), limits = c(as.Date("2020-03-01"), as.Date("2021-12-15"))) +
  scale_fill_manual(values = cols) +
  labs(x = "Date", y = "Frequency", fill = "Clade") +
  theme_classic() +
  theme(axis.text = element_text(size = 10.5, family = plot_font), axis.title = element_text(size = 12, family = plot_font), 
        legend.position = "right", 
        legend.text = element_text(size = 10.5, family = plot_font), legend.title = element_text(size = 12, family = plot_font)) 


row2 <- ggarrange(gisaid_freq, prop_vaccinated, nrow = 1, labels = c("b", "c"), font.label = list(font = plot_font))
fig_2 <- ggarrange(plot_gmobility, row2, nrow = 2, labels = c("a"), font.label = list(font = plot_font))
ggsave(filename = here(output_folder, "figure-2.tiff"), fig_2, width = 360, height = 270, units = "mm", bg="white", dpi = 300)

```

```{r, fig.width = 15, fig.height = 9}
fig_2
```

